export const data = {
  nav_options: [{ name: 'Overview', _id: 'overview', location: '/' }],
  bodies_info: [
    {
      _id: '1101',
      name: 'level 4',
      status: 'pending',
      description: 'water',
      percentage: 16,
      progress: 'dam',
      createdAt: 1623703372000,
    },
    {
      _id: '111884',
      name: 'Software dev',
      status: 'finished',
      description: 'water',
      percentage: 100,
      progress: 'sump',
      createdAt: 1623703372000,
    },
    {
      _id: '1114',
      name: 'level 20',
      status: 'in-progress',
      description: 'water',
      percentage: 40,
      progress: 'sump',
      createdAt: 1623703372000,
    },
    {
      _id: '1114',
      name: 'home work',
      status: 'in-progress',
      description: 'do my thesis homework',
      percentage: 40,
      progress: 'sump',
      createdAt: 1001010,
    },
  ],
};
